Black		EQU     00h
Blue		EQU	01h
Green		EQU	02h
Cyan		EQU	03h
Red		EQU	04h
Magenta		EQU	05h
Brown		EQU	06h
White		EQU	07h

Gray		EQU	08h
BrBlue		EQU	09h
BrGreen		EQU	0Ah
BrCyan		EQU	0Bh
BrRed		EQU	0Ch
BrMagenta	EQU	0Dh
Yellow		EQU	0Eh
BrWhite		EQU	0Fh

BakBlack	EQU	00h
BakBlue		EQU	10h
BakGreen	EQU	20h
BakCyan		EQU	30h
BakRed		EQU	40h
BakMagenta	EQU	50h
BakBrown	EQU	60h
BakWhite	EQU	70h

Blink		EQU	80h
