#
# Tools used to compile this project:
#
#   Open Watcom 11.9
#   Netwide Assembler 2.15
#   Borland TASM 5.1 (for advanced boot manager)

compiler        = wcl
compiler_flags  = -q -ml -bcl=dos -w4
assembler       = nasm
assembler_flags = -f obj
linker          = wlink
linker_flags    =

tasm       = tasm
tasm_flags = /ml /m3 /t

part_c_objects   = part.obj part_aux.obj part_gen.obj part_gui.obj part_htm.obj
part_c_objects  += part_ide.obj part_msg.obj
part_c_objects  += s_fat16.obj s_fat32.obj s_unknwn.obj
part_asm_objects = screen.obj diskio.obj ipl.obj ipl2.obj fat_boot.obj
manager_objects  = manager.obj
part_objects     = $(part_c_objects) $(part_asm_objects) $(manager_objects)

header_files = part.h diskio.h screen.h

all : part.exe

part.exe : $(part_objects) part.lnk
	$(linker) @part

part.lnk : $(part_objects) MAKEFILE
   @echo NAME $^& >$^@
   @echo SYSTEM DOS >>$^@
   @echo OPTION QUIET >>$^@
   @echo OPTION MAP >>$^@
   @for %i in ($(part_objects)) do @echo FILE %i >>$^@

.c.obj : $(header_files)
   $(compiler) -c $(compiler_flags) $<

.asm.obj : 
   $(assembler) $(assembler_flags) $< -o $@

manager.obj :: manager.asm colors.inc
   $(tasm) $(tasm_flags) $^*.asm
   
mesg.exe :  support\mesg.c
   $(compiler) $(compiler_flags) $<

keycodes.exe : support\keycodes.c screen.obj screen.h
   $(compiler) $(compiler_flags) support\keycodes.c screen.obj

clean :  .SYMBOLIC
   if exist *.bak @rm *.bak
   if exist *.err @rm *.err
   if exist *.lnk @rm *.lnk
   if exist *.lst @rm *.lst
   if exist *.map @rm *.map
   if exist *.obj @rm *.obj
   if exist *.tmp @rm *.tmp

