#
# Tools used to compile this project:
#
#   MAKE Version 3.6  Copyright (c) 1991 Borland International
#   Borland C++ Version 3.10 Copyright (c) 1992 Borland International
#   Turbo Link  Version 5.1 Copyright (c) 1992 Borland International
#   Turbo Assembler  Version 3.1  Copyright (c) 1992 Borland International
#

CC = wcl -q -ml -bcl=dos
AS = tasm /ml /m3 /t
NASM = nasm
LD = wlink

#INC  = part.h conio.h diskio.h

OBJ = part.obj part_aux.obj part_gen.obj part_gui.obj part_htm.obj &
      part_ide.obj part_msg.obj s_fat16.obj s_fat32.obj s_unknwn.obj &
      screen.obj diskio.obj ipl.obj ipl2.obj fat_boot.obj manager.obj 

all: part.exe

part.exe: $(OBJ)
	$(LD) @part
	
.c.obj:
   $(CC) -c $<

screen.obj: screen.asm
   $(NASM) -f obj $< -o $@

diskio.obj: diskio.asm
   $(NASM) -f obj $< -o $@

ipl.obj: ipl.asm
   $(NASM) -f obj $< -o $@

ipl2.obj: ipl2.asm
   $(NASM) -f obj $< -o $@

fat_boot.obj: fat_boot.asm
#   $(AS) $<
   $(NASM) -f obj $< -o $@

manager.obj: manager.asm
   $(AS) $<
   
#.asm.obj:
#   $(AS) $<

mesg:  mesg.c
   $(CC) mesg.c
   del mesg.obj

keys: keycodes.c screen.obj screen.h
   $(CC) keycodes.c screen.obj
   del keycodes.obj

clean:
   del *.obj
   del *.map
   del *.lst
   del *.tmp
